export const ROLES = { ADMIN: 'ADMIN', CASHIER: 'CASHIER', CUSTOMER: 'CUSTOMER' }

export const STOCK_STATUS = { IN_STOCK: 'IN_STOCK', LOW_STOCK: 'LOW_STOCK', OUT_OF_STOCK: 'OUT_OF_STOCK' }

export const DATE_FORMATS = { DISPLAY: 'DD/MM/YYYY', API: 'YYYY-MM-DD' }

export const PAGINATION = { DEFAULT_PAGE_SIZE: 20 }

